### ISSUE TITLE
Script appears to get errors on current version with Windows 10 1709/1803 at runtime

### ISSUE THREAD

**Issue by esparks-ipl** [arcadesdude/BRU#1] opened 2018-05-09 00:22 UTC
Bloatware-Removal-Utility.ps1:2158 char:29
+             if ($_.Checked) {
+                             ~
Missing closing '}' in statement block or type definition.

etc. 

in about 5 different locations.  

Previous version 03-01-2018 works

**Comment by arcadesdude** [comment] 2018-05-16 01:25
Thanks for feedback. Looking into it. Seems my indentation in function selectedProgsListviewtoArray is one too many and may have thrown me off there. Next release will hopefully fix that and also detect more Win10 bloatware from 1803.

**Comment by arcadesdude** [comment] 2018-05-16 13:00
@esparks-ipl, Can you send your log file with the errors here? I've used it plenty on 1709 builds and not seeing the error but I have run it but only a few times so far on 1803. Thanks

**Comment by esparks-ipl** [comment] 2018-05-16 17:52
Unfortunately I don't have access to the systems anymore as they're at a disconnected site now. 

Next one I get I'll post if it errors.

Thanks for your work on this script!

**Comment by arcadesdude** [comment] 2018-05-30 10:19
I've done lots of testing on newest version now and can't repeat reported error. Research shows it could be a character encoding issue or a bad switch option -option or missing parentheses. I did clean up the indentation in that section of the script but haven't seen that specific error on the latest 1803 (or previous versions of Windows 10). 

I have seen Windows 10 on versions 1703 and prior act funny when it doesn't  have all the windows updates. Be sure to run windows updates first and reboot prior to running this script to alleviate that wonkiness. Will release new version soon so try that once it is out and see if you still have issues or steps to reproduce + logs. Closing this as non repeatable.  Thanks!

**Closed as completed** 2018-05-30 10:19 UTC

**Comment by arcadesdude** [comment] 2018-10-01 20:29
I found out this issue was due to copying and pasting into GitHub. I now either upload files or use git to push them up without issues. Might have been file encoding or githubs editor parsing. All good now and I know to avoid pasting into github's editor.
